### ISSUE TITLE
Allow to have filesource coming from environment variables

### ISSUE THREAD

**Issue by roman** [roman/Haskell-etc#20]
### Context

When specifying a filepath source, allow fetching one from an environment variable, this value should have the highest precedence over others (e.g. should be indexed last)

### Implementation Details

* Enhance the File Config Entry to have a env var source field
* Update syntax for spec filepaths entry

Supported entries:

without env var entry
```yaml
etc/filepaths:
- file1
- file2
```
with env var entry
```yaml
etc/files:
  env: PROJECT_CONFIG_FILE
  paths:
  - path1
  - path2 
```
