### ISSUE TITLE
Fix type field on etc/entries cli

### ISSUE THREAD

**Issue by cmditch** [roman/Haskell-etc#41]
```yaml
etc/entries:
  dev:
    build-db:
      etc/spec:
        default: false
        cli:
          input: option
          type: switch
          required: false
          long: dev-build-db
          metavar: MIGRATE AND SEED
```
upon compile, will result in:

`InvalidConfiguration Nothing "Error in $['etc/entries'].dev.cli: cli option contains invalid key \"type\""`, despite what is described here https://github.com/roman/Haskell-etc#cli-entries

This was also mentioned in issue https://github.com/roman/Haskell-etc/issues/37 under "Other".

Might also be related to the change discussed in issue https://github.com/roman/Haskell-etc/issues/38

PS - Really enjoying the library @roman, thanks!

**Comment by roman** [comment]
@cmditch Yes, the documentation is misleading given the contract of where `type` is changed and I didn't update the README 🤦‍♂️.

I updated the README to avoid new people falling into that, let me know if this change is enough to make the error go away; If so, feel free to close this ticket, otherwise, send me a new comment with:

* a config spec
* a config file example
* an error message
* what were you expecting instead

Thank you very much for reporting your issues, keep them coming.

Cheers.

**Comment by cmditch** [comment]
Ah.

I think the problem I'm running into is making an `option` that takes no input.

So `my-haskell-exe --verbose` makes verbose `true`, instead of the current `my-haskell-exe --verbose true`.

Though perhaps this is not possible, unless one defines an additional `input` type.
Something like `argument`, `option`, and `flag`?

**Comment by roman** [comment]
Uhmm, by using the `type: bool` on the `etc/cli` map it does not work?

**Comment by cmditch** [comment]
Doesn't seem to.
```
etc/entries:
  dev:
    build-db:
      etc/spec:
        default: false
        type: bool
        cli:
          input: option
          required: false
          long: dev-build-db
          metavar: MIGRATE AND SEED
```
I get: `The option `--dev-build-db` expects an argument.`

and for
```
  dev:
    build-db:
      etc/spec:
        default: false
        cli:
          type: bool
          input: option
          required: false
          long: dev-build-db
          metavar: MIGRATE AND SEED
```
`opportunity-service-exe: InvalidConfiguration Nothing "Error in $['etc/entries'].dev.cli: cli option contains invalid key \"typ`
