### ISSUE TITLE
CLI entry with string type does not accept numbers

### ISSUE THREAD

**Issue by roman** [roman/Haskell-etc#48]
### Current

When having a configuration spec like the following:

```
etc/entries:
    amount:
      etc/spec:
        type: "string"
        required: true
        cli:
          input: "argument"
          metavar: "AMOUNT"
```

And then call the program with:

```
program 100
```

It will complain with the error message `invalid input`.

### Expected

It should work as expected

### Implementation notes:

* Is likely a bug in the [`jsonOptReader`](https://github.com/roman/Haskell-etc/blob/master/etc/src/System/Etc/Internal/Resolver/Cli/Common.hs#L86) function
