### ISSUE TITLE
Throw error when same option is used in multiple entries

### ISSUE THREAD

**Issue by roman** [roman/Haskell-etc#66]
## Context

When specifying multiple entries in a configuration map with the same CLI configuration, a warning or error should be displayed

## Input

```
hello:
  etc/spec:
    cli:
      input: option
      long: hello
      command:
      - one
hola:
  etc/spec:
    cli:
      input: option
      long: hello
      command:
      - one
```

Both `hello` and `hola` have the exact same CLI configuration, this should throw an error
