### ISSUE TITLE
Stackage LTS-14.0 failure

### ISSUE THREAD

**Issue by spacekitteh** [roman/Haskell-etc#68]
I have the YAML and CLI flags enabled.

```etc               > src\System\Etc\Internal\Resolver\Cli\Common.hs:151:7: error:
etc               >     Ambiguous occurrence `exitSuccess'
etc               >     It could refer to either `RIO.exitSuccess',
etc               >                              imported from `RIO' at src\System\Etc\Internal\Resolver\Cli\Common.hs:10:1-20
etc               >                              (and originally defined in `rio-0.1.11.0:RIO.Prelude.Exit')
etc               >                           or `System.Exit.exitSuccess',
etc               >                              imported from `System.Exit' at src\System\Etc\Internal\Resolver\Cli\Common.hs:21:1-18
etc               >     |
etc               > 151 |       exitSuccess
etc               >     |       ^^^^^^^^^^^
etc               >
etc               > src\System\Etc\Internal\Resolver\Cli\Common.hs:155:7: error:
etc               >     Ambiguous occurrence `exitWith'
etc               >     It could refer to either `RIO.exitWith',
etc               >                              imported from `RIO' at src\System\Etc\Internal\Resolver\Cli\Common.hs:10:1-20
etc               >                              (and originally defined in `rio-0.1.11.0:RIO.Prelude.Exit')
etc               >                           or `System.Exit.exitWith',
etc               >                              imported from `System.Exit' at src\System\Etc\Internal\Resolver\Cli\Common.hs:21:1-18
etc               >     |
etc               > 155 |       exitWith exitCode
`

**Comment by spacekitteh** [comment]
This still occurs in 14.1. @qrilka

**Comment by qrilka** [comment]
@spacekitteh I couldn't reproduce it:
```
qrilka@qdesktop ~/ws/h/Haskell-etc $ stack build --stack-yaml=stack-lts-14.1.yaml && echo "exit code: $?"
exit code: 0
qrilka@qdesktop ~/ws/h/Haskell-etc $ cat stack-lts-14.1.yaml
resolver: lts-14.1
packages:
- 'etc'
- 'examples/etc-command-example'
- 'examples/etc-plain-example'
- 'examples/etc-embedded-config-example'
- 'examples/etc-compile-time-spec-check-example'
flags:
  etc:
    extra: true
    cli: true
    yaml: true
```
I use Stack-2.1

**Comment by spacekitteh** [comment]
Hmm. Perhaps it is a windows-only bug?

**Comment by spacekitteh** [comment]
Nope. Bizarre, when I used just that config, it worked; but when I include etc as a dependency in another project, and use lts-14.0 or 14.1 or 14.6, I get that error.

I *am* using Stack 2.2.0 (git), but I'm 99.9% sure it was occurring with 2.1 as well.

**Comment by spacekitteh** [comment]
Here's the project: http://gitlab.com/spacekitteh/curiosity.git

**Comment by qrilka** [comment]
Oh, I guess I see what's the problem: the library had no release since 0.4.1.0 and #67 has landed after that. Until @roman releases a new version you could add the current commit 5c88575 as a dependency into your stack.yaml. Hope this helps.

**Comment by TOTBWF** [comment]
I'm also experiencing this, would it make sense to cut a release soon?

**Comment by qrilka** [comment]
@TOTBWF maybe it could make sense to contact @roman using some other means than Github - it could be possible that he has no time to maintain the package and new maintainer is needed.

**Comment by roosemberth** [comment]
I'm hitting this aswell :( Is there any workaround ?

**Comment by qrilka** [comment]
you could use the commit mentioned above @roosemberth

**Comment by roosemberth** [comment]
@qrilka Yes, sorry I didn't know how stack distributions work ><"

I added this to my stack configuration:

```yaml
extra-deps:
- git: https://github.com/roman/Haskell-etc
  commit: 5c88575fa5d742aece4669c460e0ae72e039b45e
  subdir: etc
```
